### ISSUE TITLE
[Suggestion] add option to use Hono.basePath() to host app so it can be hosted on the same port as the main Invidious instance

### ISSUE THREAD

**Issue by Yetangitu** [iv-org/invidious-companion#118]
The title says it all: adding the option to host invidious-companion on the same port as the main Invidious instance by using `Hono.basePath('/companion')`  (or whatever the administrator puts in the configuration file for the base path) takes away the need to allow access or forward another port to the server running IC, instead forwarding calls to '/companion' to the app in the reverse proxy configuration. Something like this:

``` yaml
invidious_companion:
  - private_url: "http://192.168.1.51:3011/"
    public_url: "https://tube.example.org/companion"
invidious_companion_key: "abcdefghijklmnop"
```

``` toml
[server]
port = 3011 # env variable: PORT
host = "192.168.1.51" # env variable: HOST
base_path = "/companion" # env variable BASE_PATH
# # secret key needs to be 16 characters long or more
secret_key = "abcdefghijklmnop" # env variable: SERVER_SECRET_KEY
```

Add the selected base path to the constructor in `src/routes/index.ts` (see https://github.com/honojs/hono/issues/1531) and adapt the interface in Invidious to use the correct base path (inferred from `private_url`) when communicating with the companion.
