### ISSUE TITLE
handle hls for apple devices and hls livestream

### ISSUE THREAD

**Issue by unixfox** [iv-org/invidious-companion#7]

**Comment by jve-engineering** [comment]
Is there any update regarding support for live streams? With the latest release (cb8d9bb) and [v2.20260207.0](https://github.com/iv-org/invidious/releases/tag/v2.20260207.0) I'm still getting the error messages messages mentioned in #192.

**Comment by akellbl4** [comment]
I'm more than happy to open a PR with livestream support.

I've implemented live stream support in [a fork](https://github.com/crutchcrew/invidious-companion/commit/9e54b554e1ee1c46725fc39fb8a48c21bd989c7b).
Implementation is based on FreeTube livestream handling.

For testing in docker add `build` section and change image name
```
build:
      context: https://github.com/crutchcrew/invidious-companion.git#master
      args:
        # the Dockerfile bind-mounts .git, which BuildKit strips from git contexts by default
        BUILDKIT_CONTEXT_KEEP_GIT_DIR: 1
    image: invidious-companion:crutchcrew
```
