### ISSUE TITLE
Companion stuck in loop, no error, except the "Not implemented"

### ISSUE THREAD

**Issue by fl0wfr** [iv-org/invidious-companion#93]
Hi,

I followed the instructions to move from inv_sig_helper to companion, but the container is always stuck with the following error:

```
[INFO] No local config file found, using default config
Loaded Configuration {
  server: {
    port: 8282,
    host: "0.0.0.0",
    secret_key: "ieth9ip5iNg1woeM",
    verify_requests: false,
    encrypt_query_params: false
  },
  cache: { enabled: true, directory: "/var/tmp" },
  networking: { ump: false, proxy: null },
{
    youtube_session: { po_token_enabled: true, frequency: "*/5 * * * *" }
  },
  youtube_session: { oauth_enabled: false, cookies: "" }
}
[INFO] job po_token is active.
[INFO] the "Not implemented: HTMLCanvasElement.prototype.getContext" error is normal. Please do not open a bug report about it.
Error: Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package)
    at module.exports (file:///tmp/deno-compile-invidious_companion/.deno_compile_node_modules/localhost/jsdom/26.0.0/lib/jsdom/browser/not-implemented.js:9:17)
    at HTMLCanvasElementImpl.getContext (file:///tmp/deno-compile-invidious_companion/.deno_compile_node_modules/localhost/jsdom/26.0.0/lib/jsdom/living/nodes/HTMLCanvasElement-impl.js:42:5)
    at HTMLCanvasElement.getContext (file:///tmp/deno-compile-invidious_companion/.deno_compile_node_modules/localhost/jsdom/26.0.0/lib/jsdom/living/generated/HTMLCanvasElement.js:131:58)
    at eval (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at poTokenGenerate (file:///tmp/deno-compile-invidious_companion/app/src/lib/jobs/potoken.ts:52:5))))), <anonymous>:1:179)
    at Iq (eval at <anonymous> (eval at poTokenGenerate (file:///tmp/deno-compile-invidious_companion/app/src/lib/jobs/potoken.ts:52:5)), <anonymous>:7578:37757)
    at K.eval [as Z] (eval at <anonymous> (eval at poTokenGenerate (file:///tmp/deno-compile-invidious_companion/app/src/lib/jobs/potoken.ts:52:5)), <anonymous>:7578:54192)
    at u3 (eval at <anonymous> (eval at poTokenGenerate (file:///tmp/deno-compile-invidious_companion/app/src/lib/jobs/potoken.ts:52:5)), <anonymous>:7578:23514)
    at H4 (eval at <anonymous> (eval at poTokenGenerate (file:///tmp/deno-compile-invidious_companion/app/src/lib/jobs/potoken.ts:52:5)), <anonymous>:7578:9438)
    at v4 (eval at <anonymous> (eval at poTokenGenerate (file:///tmp/deno-compile-invidious_companion/app/src/lib/jobs/potoken.ts:52:5)), <anonymous>:7578:12196)
    at VH (eval at <anonymous> (eval at poTokenGenerate (file:///tmp/deno-compile-invidious_companion/app/src/lib/jobs/potoken.ts:52:5)), <anonymous>:7578:36476) undefined
[INFO] the "Not implemented: HTMLCanvasElement.prototype.getContext" error is normal. Please do not open a bug report about it.
Error: Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package)
    at module.exports (file:///tmp/deno-compile-invidious_companion/.deno_compile_node_modules/localhost/jsdom/26.0.0/lib/jsdom/browser/not-implemented.js:9:17)
    at HTMLCanvasElementImpl.getContext (file:///tmp/deno-compile-invidious_companion/.deno_compile_node_modules/localhost/jsdom/26.0.0/lib/jsdom/living/nodes/HTMLCanvasElement-impl.js:42:5)
    at HTMLCanvasElement.getContext (file:///tmp/deno-compile-invidious_companion/.deno_compile_node_modules/localhost/jsdom/26.0.0/lib/jsdom/living/generated/HTMLCanvasElement.js:131:58)
    at eval (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at poTokenGenerate (file:///tmp/deno-compile-invidious_companion/app/src/lib/jobs/potoken.ts:52:5))))), <anonymous>:1:179)
    at Iq (eval at <anonymous> (eval at poTokenGenerate (file:///tmp/deno-compile-invidious_companion/app/src/lib/jobs/potoken.ts:52:5)), <anonymous>:6424:37757)
    at K.eval [as Z] (eval at <anonymous> (eval at poTokenGenerate (file:///tmp/deno-compile-invidious_companion/app/src/lib/jobs/potoken.ts:52:5)), <anonymous>:6424:54192)
    at u3 (eval at <anonymous> (eval at poTokenGenerate (file:///tmp/deno-compile-invidious_companion/app/src/lib/jobs/potoken.ts:52:5)), <anonymous>:6424:23514)
    at H4 (eval at <anonymous> (eval at poTokenGenerate (file:///tmp/deno-compile-invidious_companion/app/src/lib/jobs/potoken.ts:52:5)), <anonymous>:6424:9438)
    at v4 (eval at <anonymous> (eval at poTokenGenerate (file:///tmp/deno-compile-invidious_companion/app/src/lib/jobs/potoken.ts:52:5)), <anonymous>:6424:12196)
    at VH (eval at <anonymous> (eval at poTokenGenerate (file:///tmp/deno-compile-invidious_companion/app/src/lib/jobs/potoken.ts:52:5)), <anonymous>:6424:36476) undefined
```

My compose:

```
version: "3"
services:

  invidious:
    image: quay.io/invidious/invidious:master
    container_name: invidious
    restart: unless-stopped
    environment:
      INVIDIOUS_CONFIG: |
        db:
          dbname: invidious
          user: invidious
          password: redacted
          host: invidious-db
          port: 5432
        check_tables: true
        invidious_companion:
          - private_url: "http://companion:8282"
            public_url: "https://invidiouscompanion.domain.tld"
        invidious_companion_key: "redacted"
        visitor_data: redacted
        po_token: redacted
        captcha_enabled: false
        default_user_preferences:
          locale: fr
          region: FR
        external_port: 443
        domain: invidious.domain.tld
        https_only: true
        hmac_key: redacted
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:3000/api/v1/trending || exit 1
      interval: 30s
      timeout: 5s
      retries: 2
    depends_on:
      - invidious-db
      - companion
    dns:
      - "8.8.8.8"
      - "8.8.4.4"
    logging:
        options:
            tag: "{{.Name}}"
            syslog-address: udp://127.0.0.1:514
        driver: syslog
    runtime: runc
    networks:
      - invidious

  companion:
    image: quay.io/invidious/invidious-companion:latest
    container_name: invidious-companion
    environment:
       - SERVER_SECRET_KEY=redacted
    restart: unless-stopped
    cap_drop:
      - ALL
    read_only: true
    volumes:
      - /docker/companioncache:/var/tmp/youtubei.js:rw
    security_opt:
      - no-new-privileges:true
    ports:
      - "127.0.0.1:8282:8282"
    logging:
        options:
          tag: "{{.Name}}"
          syslog-address: udp://127.0.0.1:514
        driver: syslog
    runtime: runc
    networks:
      - invidious

  invidious-db:
    image: docker.io/library/postgres:14
    container_name: invidious-db
    restart: unless-stopped
    volumes:
      - /docker/DB/Invidious:/var/lib/postgresql/data
      - /docker/Invidious/config/sql:/config/sql
      - /docker/Invidious/docker/init-invidious-db.sh:/docker-entrypoint-initdb.d/init-invidious-db.sh
    environment:
      POSTGRES_DB: invidious
      POSTGRES_USER: invidious
      POSTGRES_PASSWORD: redacted
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
    logging:
        options:
            tag: "{{.Name}}"
            syslog-address: udp://127.0.0.1:514
        driver: syslog
    runtime: runc
    networks:
      - invidious
```

When trying to load a video from Invidious, I get the following error: "Error connecting to 'companion:8282': Connection refused" which seems totally normal because of companion constantly restarting.
Did I miss something or is there in fact a bug?

Thanks!
